modelmanager_version: 0.1.dev20

saved_object:
    choice_column: TOD
    filters: null
    initial_coefs:
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    model_expression: null
    model_expression_keys:
    - intercept
    - da_Time_AM_MD
    - da_Time_AM_PM
    - da_Time_AM_EV
    - da_Time_MD_MD
    - da_Time_MD_PM
    - da_Time_MD_EV
    - sector_constr
    - sector_mfg
    - sector_retail
    - info
    - finance
    - scitech
    - sector_edu_serv
    - sector_healthcare
    - sector_oth_serv
    - sector_gov
    - age_16less25
    - female
    - minority
    - hh_inc_150kplus
    - lessGED
    - GED
    - somebach
    - Assoc
    - Bach
    - hours
    - hh_size_1per
    model_expression_values:
    -   - 2
        - 3
        - 12
        - 13
        - 22
        - 23
        - 24
    -   - 12
    -   - 13
    -   - 14
    -   - 22
    -   - 23
    -   - 24
    -   - 3
        - 12
    -   - 12
        - 23
    -   - 2
        - 3
        - 14
        - 23
        - 24
    -   - 2
        - 3
        - 12
    -   - 2
        - 12
        - 24
    -   - 14
    -   - 3
        - 12
        - 22
        - 24
    -   - 3
        - 23
    -   - 2
        - 3
    -   - 14
        - 22
        - 23
        - 24
    -   - 23
        - 24
    -   - 2
        - 3
    -   - 14
        - 24
    -   - 2
        - 24
    -   - 2
        - 3
    -   - 2
        - 3
    -   - 2
        - 3
    -   - 2
        - 3
    -   - 2
    -   - 3
        - 12
        - 14
        - 22
        - 23
        - 24
    -   - 22
        - 23
        - 24
    model_labels: null
    name: TOD_choice
    out_column: null
    out_filters: null
    out_tables: null
    out_transform: null
    summary_table: "                     Multinomial Logit Model Regression Results\
        \                    \n===================================================================================\n\
        Dep. Variable:                     _chosen   No. Observations:           \
        \     4,681\nModel:             Multinomial Logit Model   Df Residuals:  \
        \                  4,614\nMethod:                                MLE   Df\
        \ Model:                           67\nDate:                     Mon, 17 Dec\
        \ 2018   Pseudo R-squ.:                   0.296\nTime:                   \
        \          05:19:26   Pseudo R-bar-squ.:               0.289\nAIC:       \
        \                     13,845.902   Log-Likelihood:             -6,855.951\n\
        BIC:                            14,278.137   LL-Null:                    -9,733.866\n\
        ========================================================================================\n\
        \                           coef    std err          z      P>|z|      [0.025\
        \      0.975]\n----------------------------------------------------------------------------------------\n\
        intercept_2             -0.7288      0.400     -1.824      0.068      -1.512\
        \       0.054\nintercept_3             -0.3466      0.453     -0.766     \
        \ 0.444      -1.234       0.541\nintercept_12             4.2615      0.294\
        \     14.511      0.000       3.686       4.837\nintercept_13            \
        \ 3.8435      0.260     14.785      0.000       3.334       4.353\nintercept_22\
        \             4.0048      0.356     11.244      0.000       3.307       4.703\n\
        intercept_23             4.0123      0.313     12.830      0.000       3.399\
        \       4.625\nintercept_24             2.9939      0.332      9.023     \
        \ 0.000       2.344       3.644\nda_Time_AM_MD_12        -0.0237      0.002\
        \    -10.914      0.000      -0.028      -0.019\nda_Time_AM_PM_13        -0.0167\
        \      0.001    -11.596      0.000      -0.020      -0.014\nda_Time_AM_EV_14\
        \        -0.0184      0.002     -8.325      0.000      -0.023      -0.014\n\
        da_Time_MD_MD_22        -0.0371      0.004     -8.804      0.000      -0.045\
        \      -0.029\nda_Time_MD_PM_23        -0.0308      0.003    -11.944     \
        \ 0.000      -0.036      -0.026\nda_Time_MD_EV_24        -0.0277      0.003\
        \    -10.033      0.000      -0.033      -0.022\nsector_constr_3         \
        \ 1.2810      0.254      5.034      0.000       0.782       1.780\nsector_constr_12\
        \         1.0110      0.230      4.391      0.000       0.560       1.462\n\
        sector_mfg_12           -0.5690      0.260     -2.185      0.029      -1.079\
        \      -0.059\nsector_mfg_23           -0.7864      0.304     -2.585     \
        \ 0.010      -1.383      -0.190\nsector_retail_2          0.8089      0.230\
        \      3.514      0.000       0.358       1.260\nsector_retail_3         -1.3072\
        \      0.597     -2.191      0.028      -2.477      -0.138\nsector_retail_14\
        \         0.6161      0.216      2.851      0.004       0.193       1.040\n\
        sector_retail_23         0.4962      0.183      2.713      0.007       0.138\
        \       0.855\nsector_retail_24         1.2478      0.161      7.742     \
        \ 0.000       0.932       1.564\ninfo_2                  -1.6392      0.469\
        \     -3.492      0.000      -2.559      -0.719\ninfo_3                  -0.8759\
        \      0.306     -2.862      0.004      -1.476      -0.276\ninfo_12      \
        \           -0.8854      0.228     -3.876      0.000      -1.333      -0.438\n\
        finance_2               -0.7686      0.401     -1.915      0.055      -1.555\
        \       0.018\nfinance_12              -0.9116      0.293     -3.113     \
        \ 0.002      -1.486      -0.338\nfinance_24              -0.8152      0.317\
        \     -2.568      0.010      -1.437      -0.193\nscitech_14              \
        \ 0.4510      0.137      3.288      0.001       0.182       0.720\nsector_edu_serv_3\
        \       -0.9509      0.399     -2.385      0.017      -1.732      -0.169\n\
        sector_edu_serv_12       0.7659      0.113      6.783      0.000       0.545\
        \       0.987\nsector_edu_serv_22       0.6958      0.186      3.747     \
        \ 0.000       0.332       1.060\nsector_edu_serv_24      -0.5117      0.203\
        \     -2.521      0.012      -0.909      -0.114\nsector_healthcare_3     -0.6347\
        \      0.314     -2.019      0.044      -1.251      -0.018\nsector_healthcare_23\
        \    -0.6287      0.183     -3.439      0.001      -0.987      -0.270\nsector_oth_serv_2\
        \       -0.8793      0.438     -2.006      0.045      -1.739      -0.020\n\
        sector_oth_serv_3       -1.1758      0.526     -2.233      0.026      -2.208\
        \      -0.144\nsector_gov_14           -0.4983      0.231     -2.156     \
        \ 0.031      -0.951      -0.045\nsector_gov_22           -2.0506      0.718\
        \     -2.856      0.004      -3.458      -0.644\nsector_gov_23           -1.2396\
        \      0.281     -4.406      0.000      -1.791      -0.688\nsector_gov_24\
        \           -1.2853      0.315     -4.079      0.000      -1.903      -0.668\n\
        age_16less25_23          0.6925      0.205      3.382      0.001       0.291\
        \       1.094\nage_16less25_24          0.9264      0.202      4.589     \
        \ 0.000       0.531       1.322\nfemale_2                -0.5590      0.159\
        \     -3.511      0.000      -0.871      -0.247\nfemale_3                -0.6831\
        \      0.182     -3.763      0.000      -1.039      -0.327\nminority_14  \
        \            0.3354      0.121      2.763      0.006       0.098       0.573\n\
        minority_24              0.3887      0.122      3.195      0.001       0.150\
        \       0.627\nhh_inc_150kplus_2       -0.5333      0.211     -2.527     \
        \ 0.011      -0.947      -0.120\nhh_inc_150kplus_24      -0.3920      0.132\
        \     -2.976      0.003      -0.650      -0.134\nlessGED_2               \
        \ 3.1684      0.398      7.957      0.000       2.388       3.949\nlessGED_3\
        \                1.8962      0.342      5.547      0.000       1.226     \
        \  2.566\nGED_2                    2.5983      0.324      8.029      0.000\
        \       1.964       3.233\nGED_3                    1.0383      0.232    \
        \  4.466      0.000       0.583       1.494\nsomebach_2               2.0158\
        \      0.331      6.094      0.000       1.368       2.664\nsomebach_3   \
        \            0.6770      0.236      2.869      0.004       0.214       1.139\n\
        Assoc_2                  2.3107      0.336      6.867      0.000       1.651\
        \       2.970\nAssoc_3                  0.9696      0.245      3.960     \
        \ 0.000       0.490       1.449\nBach_2                   1.3809      0.308\
        \      4.486      0.000       0.778       1.984\nhours_3                 \
        \ 0.0180      0.008      2.266      0.023       0.002       0.034\nhours_12\
        \                -0.0431      0.004    -10.890      0.000      -0.051    \
        \  -0.035\nhours_14                 0.0454      0.005      8.753      0.000\
        \       0.035       0.056\nhours_22                -0.0625      0.006    -10.042\
        \      0.000      -0.075      -0.050\nhours_23                -0.0336    \
        \  0.005     -7.334      0.000      -0.043      -0.025\nhours_24         \
        \       -0.0172      0.005     -3.362      0.001      -0.027      -0.007\n\
        hh_size_1per_22          0.6008      0.212      2.832      0.005       0.185\
        \       1.017\nhh_size_1per_23          0.3693      0.150      2.455     \
        \ 0.014       0.074       0.664\nhh_size_1per_24          0.3629      0.162\
        \      2.240      0.025       0.045       0.681\n========================================================================================"
    supplemental_objects:
    -   content_type: pickle
        name: model-object
        required: true
    tables: tripsA
    tags:
    - TOD_choice
    - emma
    - test
    template: SmallMultinomialLogitStep
    template_version: 0.1.dev20
