modelmanager_version: 0.1.dev8

saved_object:
    alt_filters: null
    alt_sample_size: 10
    alternatives:
    - units
    - buildings
    choice_column: unit_id
    chooser_filters:
    - household_id % 1000 < 1
    choosers: households
    fitted_parameters:
    - 1.4474041623995042e-05
    model_expression: res_price_per_sqft - 1
    name: large-mnl-test
    out_alt_filters: null
    out_alternatives: null
    out_chooser_filters: null
    out_choosers: null
    out_column: null
    summary_table: "                  CHOICEMODELS ESTIMATION RESULTS            \
        \      \n===================================================================\n\
        Dep. Var.:                chosen   No. Observations:               \nModel:\
        \         Multinomial Logit   Df Residuals:                   \nMethod:  \
        \     Maximum Likelihood   Df Model:                       \nDate:       \
        \                       Pseudo R-squ.:                  \nTime:          \
        \                    Pseudo R-bar-squ.:              \nAIC:              \
        \                 Log-Likelihood:       -5,717.265\nBIC:                 \
        \              LL-Null:              -5,717.319\n=======================================================================\n\
        \                        coef   std err         z     P>|z|   Conf. Int.\n\
        -----------------------------------------------------------------------\n\
        res_price_per_sqft    0.0000     0.000     0.432                       \n\
        ======================================================================="
    tags:
    - sam
    - testing
    type: LargeMultinomialLogitStep
