name: network_aggregations

desc: Network aggregations

model_type: networks

node_col: node_id

variable_definitions:


  - name: residential_units_500
    dataframe: buildings
    varname: residential_units
    radius: 500
