name: network_aggregations

desc: Network aggregations

model_type: networks

node_col: node_id_walk

variable_definitions:


  - name: units_500_walk
    dataframe: buildings
    varname: residential_units
    radius: 500

  - name: pop_500_walk
    dataframe: households
    varname: persons
    radius: 500

  - name: poor_500_walk
    dataframe: households
    filters:
    - income < 40000
    radius: 500

  - name: renters_500_walk
    dataframe: households
    filters:
    - tenure == 2
    radius: 500

  - name: med_income_500_walk
    aggregation: median
    dataframe: households
    varname: income
    radius: 500

  - name: jobs_500_walk
    dataframe: jobs
    radius: 500

  - name: med_rent_500_walk
    dataframe: rentals
    varname: rent
    radius: 1500
    aggregation: median
    decay: flat


