name: network_aggregations

desc: Network aggregations

model_type: networks

node_col: node_id_drive

variable_definitions:


  - name: residential_units_500
    dataframe: buildings
    varname: residential_units
    radius: 500

  - name: residential_units_1500
    dataframe: buildings
    varname: residential_units
    radius: 1500

  - name: population_1500
    filters:
    dataframe: households
    varname: persons

  - name: poor_1500
    dataframe: households
    filters:
    - income < 40000
    varname: persons
    radius: 1500

  - name: renters_1500
    dataframe: households
    filters:
    - tenure == 2
    radius: 1500


  - name: med_income_1500
    aggregation: median
    dataframe: households
    varname: income

  - name: job_1500
    dataframe: jobs
    varname: job_id
    radius: 1500

  - name: ave_hhsize
    dataframe: households
    varname: persons
    radius: 1500
    aggregation: average
    decay: flat


  - name: med_rent_sqft_1500
    dataframe: rentals
    varname: price_per_sqft
    radius: 1500
    aggregation: median
    decay: flat


