name: network_aggregations

desc: Network aggregations

model_type: networks

node_col: node_id_small

variable_definitions:


  - name: residential_units_10000
    dataframe: buildings
    varname: residential_units
    radius: 10000

  - name: population_10000
    dataframe: households
    varname: persons
    radius: 10000

  - name: jobs_10000
    dataframe: jobs
    radius: 10000

  - name: jobs_25000
    dataframe: jobs
    radius: 25000

  - name: med_income_10000
    aggregation: median
    dataframe: households
    varname: income
    radius: 10000


