modelmanager_version: 0.1.dev14

saved_object:
    alt_capacity: null
    alt_filters: null
    alt_sample_size: null
    alternatives: null
    choice_column: null
    chooser_filters: null
    chooser_sample_size: null
    chooser_size: null
    choosers: null
    constrained_choices: False
    fitted_parameters:
    - 0.06558661891692624
    - 0.10223508076510335
    - -2.3850706777006505
    - 0.0002020274932527738
    max_iter: null
    model_expression: np.log1p(jobs_1500_walk) + np.log(jobs_25000) + np.log1p(tt_da)
        + tt_wTrnW - 1
    name: WLCM-baseline
    out_alt_filters: null
    out_alternatives: null
    out_chooser_filters: null
    out_choosers: null
    out_column: null
    summary_table: "                  CHOICEMODELS ESTIMATION RESULTS            \
        \      \n===================================================================\n\
        Dep. Var.:                chosen   No. Observations:          8,918\nModel:\
        \         Multinomial Logit   Df Residuals:              8,914\nMethod:  \
        \     Maximum Likelihood   Df Model:                      4\nDate:       \
        \          2018-10-10   Pseudo R-squ.:             0.418\nTime:          \
        \            19:31   Pseudo R-bar-squ.:         0.417\nAIC:              \
        \    23,923.534   Log-Likelihood:      -11,957.767\nBIC:                 \
        \ 23,951.917   LL-Null:             -20,534.454\n==============================================================================\n\
        \                              coef   std err          z     P>|z|   Conf.\
        \ Int.\n------------------------------------------------------------------------------\n\
        np.log1p(jobs_1500_walk)    0.0656     0.008      8.057     0.000        \
        \     \nnp.log(jobs_25000)          0.1022     0.007     14.575     0.000\
        \             \nnp.log1p(tt_da)            -2.3851     0.022   -109.502  \
        \   0.000             \ntt_wTrnW                    0.0002     0.000     \
        \ 6.856     0.000             \n=============================================================================="
    tags:
    - max
    template: LargeMultinomialLogitStep
    template_version: 0.1.dev14
