modelmanager_version: 0.1.dev14

saved_object:
    alt_filters: null
    alt_sample_size: null
    alternatives: null
    choice_column: null
    chooser_filters: null
    chooser_sample_size: null
    choosers: null
    fitted_parameters:
    - 0.07190344563715265
    - 0.12369532397832214
    - -2.348455449363873
    - 0.00014136552127896838
    model_expression: np.log1p(jobs_1500_walk) + np.log(jobs_25000) + np.log1p(tt_da)
        + tt_wTrnW - 1
    name: WLCM
    out_alt_filters: null
    out_alternatives: null
    out_chooser_filters: null
    out_choosers: null
    out_column: null
    summary_table: "                  CHOICEMODELS ESTIMATION RESULTS            \
        \      \n===================================================================\n\
        Dep. Var.:                chosen   No. Observations:          8,918\nModel:\
        \         Multinomial Logit   Df Residuals:              8,914\nMethod:  \
        \     Maximum Likelihood   Df Model:                      4\nDate:       \
        \          2018-09-26   Pseudo R-squ.:             0.411\nTime:          \
        \            20:29   Pseudo R-bar-squ.:         0.411\nAIC:              \
        \    24,200.705   Log-Likelihood:      -12,096.352\nBIC:                 \
        \ 24,229.088   LL-Null:             -20,534.454\n==============================================================================\n\
        \                              coef   std err          z     P>|z|   Conf.\
        \ Int.\n------------------------------------------------------------------------------\n\
        np.log1p(jobs_1500_walk)    0.0719     0.008      9.003     0.000        \
        \     \nnp.log(jobs_25000)          0.1237     0.007     17.655     0.000\
        \             \nnp.log1p(tt_da)            -2.3485     0.022   -108.200  \
        \   0.000             \ntt_wTrnW                    0.0001     0.000     \
        \ 4.800     0.000             \n=============================================================================="
    tags: []
    template: LargeMultinomialLogitStep
    template_version: 0.1.dev14
