modelmanager_version: 0.1.dev14

saved_object:
    alt_filters: null
    alt_sample_size: null
    alternatives: null
    choice_column: null
    chooser_filters: null
    chooser_sample_size: null
    choosers: null
    fitted_parameters:
    - 0.0683092241052872
    - 0.06996908591554304
    - -2.3677542944006396
    - 7.96739632523685e-15
    - -0.29493260894695505
    - 0.3149856339154794
    - 0.47067398980424324
    - 0.91325090991278
    - -0.11654282560080315
    - -0.715119010523994
    - 1.3157221440910647
    - 0.909206891568516
    - -0.0003321472907666171
    - -8.763762091120108e-05
    - 4.2002390386680206e-06
    - 0.0002924116794963534
    - 0.00013986200107596788
    - 9.593594128418307e-05
    - -0.0004483836085968317
    - -0.000106180173879327
    - 0.0001876524234655807
    model_expression: np.log1p(jobs_1500_walk) + np.log(jobs_25000) + np.log1p(tt_da)
        + age*(retail + fire + healthcare + tech + mfg + food_and_hosp + edu_serv
        + gov) + tt_wTrnW - 1
    name: WLCM-age-sector
    out_alt_filters: null
    out_alternatives: null
    out_chooser_filters: null
    out_choosers: null
    out_column: null
    summary_table: "                  CHOICEMODELS ESTIMATION RESULTS            \
        \      \n===================================================================\n\
        Dep. Var.:                chosen   No. Observations:          8,918\nModel:\
        \         Multinomial Logit   Df Residuals:              8,897\nMethod:  \
        \     Maximum Likelihood   Df Model:                     21\nDate:       \
        \          2018-10-10   Pseudo R-squ.:             0.452\nTime:          \
        \            20:43   Pseudo R-bar-squ.:         0.451\nAIC:              \
        \    22,546.933   Log-Likelihood:      -11,252.466\nBIC:                 \
        \ 22,695.945   LL-Null:             -20,534.454\n==============================================================================\n\
        \                              coef   std err          z     P>|z|   Conf.\
        \ Int.\n------------------------------------------------------------------------------\n\
        np.log1p(jobs_1500_walk)    0.0683     0.008      8.132     0.000        \
        \     \nnp.log(jobs_25000)          0.0700     0.008      9.231     0.000\
        \             \nnp.log1p(tt_da)            -2.3678     0.022   -106.678  \
        \   0.000             \nage                         0.0000     0.000     \
        \ 0.000     1.000             \nretail                     -0.2949     0.064\
        \     -4.593     0.000             \nfire                        0.3150  \
        \   0.067      4.673     0.000             \nhealthcare                  0.4707\
        \     0.057      8.310     0.000             \ntech                      \
        \  0.9133     0.048     18.973     0.000             \nmfg               \
        \         -0.1165     0.065     -1.791     0.073             \nfood_and_hosp\
        \              -0.7151     0.088     -8.104     0.000             \nedu_serv\
        \                    1.3157     0.061     21.618     0.000             \n\
        gov                         0.9092     0.068     13.448     0.000        \
        \     \nage:retail                 -0.0003     0.000     -1.059     0.290\
        \             \nage:fire                   -0.0001     0.000     -0.300  \
        \   0.764             \nage:healthcare              0.0000     0.000     \
        \ 0.017     0.987             \nage:tech                    0.0003     0.000\
        \      1.404     0.160             \nage:mfg                     0.0001  \
        \   0.000      0.479     0.632             \nage:food_and_hosp           0.0001\
        \     0.000      0.272     0.785             \nage:edu_serv              \
        \ -0.0004     0.000     -1.409     0.159             \nage:gov           \
        \         -0.0001     0.000     -0.340     0.734             \ntt_wTrnW  \
        \                  0.0002     0.000      6.243     0.000             \n=============================================================================="
    tags:
    - max
    template: LargeMultinomialLogitStep
    template_version: 0.1.dev14
